FROM node:14.18.1
# create destination directory
RUN mkdir /opt/aggregroup && mkdir /opt/aggregroup/frontend
WORKDIR /opt/aggregroup/frontend/
COPY /package*.json /opt/aggregroup/frontend/
# update and install dependency
RUN apt-get update && apt-get upgrade --yes
RUN apt-get --yes install \    
    && npm install \
    && apt-get clean
# copy the app, note .dockerignore
COPY . .

