version: '3.9'

services: 
    postgres:
        image: postgres:12.8
        container_name: aggregroup-v3-db.dev
        volumes:
            - pgdata2:/var/lib/postgresql/data
            - /tmp/backup:/backup
        environment:
            POSTGRES_DB: aggregroup
            POSTGRES_USER: aggregroup_user
            POSTGRES_PASSWORD: aggregroup_user        
        restart: always    
    
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: aggregroup-v3-web.dev
        ports:
            - "3000:3000"
        environment:
            HOST: 0.0.0.0
        volumes: 
            - ./frontend:/opt/aggregroup/frontend
        restart: always       
        command: >
            sh -c "npm install &&
            npm run dev"
      
        
volumes:
    pgdata2: 


          
